import Vue from 'vue'
import {MLInstaller, MLCreate, MLanguage} from 'vue-multilanguage'

Vue.use(MLInstaller);

export default new MLCreate({
    initial: 'ar',
    // development  , production
    save: process.env.NODE_ENV === 'development',
    languages: [
        new MLanguage('en').create({
            ar: 'Arabic language',
            en: 'Arabic language',
            notification: 'Notification',
            settings: 'Settings',
            search: 'Search',
            add: 'Add',
            edit: 'Edit',
            dashboard: 'dashboard',
            welcome: 'welcome',
            admin: 'welcome',
        }),

        new MLanguage('ar').create({
            ar: 'اللغة الانجليزية',
            en: 'اللغة الانجليزية',
            notification: 'الاشعارات',
            settings: 'الاعدادات',
            search: 'البحث',
            add: 'اضافة',
            edit: 'تعديل',
            dashboard: 'لوحة التحكم',
            welcome: 'مرحبا',
            admin: 'المدير المسئول',
            mandoob: 'المندوبين',
            managers: 'المشرفين',
            clients: 'الوكلاء والموزعين',
            logout: 'تسجيل الخروج',
            email: 'البريد الالكتروني',
            firstname: 'الاسم الاول',
            lastname: 'الاسم الاخير',
            type: 'النوع',
            operations: 'عمليات',
            login: 'تسجيل الدخول',
            sign_in: 'دخول',
            password: 'كلمة المرور',
            yes: 'نعم',
            no: 'ﻻ',
            confirm_warning: 'تنبيه',
            are_you_sure: 'هل انت متأكد ؟',
            name: 'الاسم',
            mobile: 'الهاتف المحمول',
            phone: 'الهاتف الارضي',
            address: 'العنوان  ',
            status: 'الحالة',
            transactionStatus: 'حجم التعاملات  ',
            government: 'المحافظة',
            city: 'المدينة',
            loading: 'جاري التحميل',
            success: 'نجاح',
            error: 'خطأ',
            success_msg: 'تمت العملية بنجاح',
            error_msg: 'حدث خطأ',
            first_name: 'الاسم الاول',
            last_name: 'الاسم الاخير',
            supervisor: 'المراقبين',
            cost: 'التكلفة',
            cities: 'المناطق',
            customers: 'العملاء',
            customer_experience: 'خبرة العميل',
            customer_type: 'نوع العميل',
            username: 'اسم المستخدم',
            coupons: 'الكوبونات',
            code: 'الكود',
            value: 'القيمة',
            created_at: 'تاريخ الانشاء',
            delivered_at: 'تاريخ التوصيل',
            finished_at: 'تاريخ الانتهاء',
            add_coupon_value: 'اضافة قيم الكوبون',
            mandoob_collect_report: 'تقرير بتحصيلات مندوب',
            mandoob_expenses_report: 'تقرير باجمالي المصاريف',
            expenses_report: 'تقرير باجمالي المصاريف',
            mandoob_coupons_report: 'تقرير بحالات الكوبون',
            coupons_report: 'تقرير بحالات الكوبون',
            mandoob_visits_report: 'تقرير بالزيارات',
            visits_report: 'تقرير بالزيارات',
            mandoob_clients_report: 'تقرير بجميع العملاء',
            client_report: 'تقرير بجميع العملاء',
            date: 'التاريخ',
            detail: 'البيان',
            person: 'الشخص',
            start_date: 'وقت البداية',
            end_date: 'وقت النهاية',
            attendance: 'الغياب'
        })
    ]
})
